name: Build and Deploy Documentation

on:
  release:
    types:
      - published
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out PROJECT_NAME
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: build
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: Install PROJECT_NAME and build requirements
        run: |
          conda install --file requirements/build.txt
          conda install --file requirements/run.txt
          conda install --file requirements/docs.txt
          python -m pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: build documents
        run: make -C doc html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/build/html
