name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out diffpy.srfit
        uses: actions/checkout@v4

      - name: Initialize miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          auto-update-conda: true
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda config
        run: >-
          conda config --set always_yes yes
          --set changeps1 no

      - name: Install diffpy.srfit and requirements
        run: |
          conda install --file requirements/run.txt
          conda install --file requirements/build.txt
          conda install --file requirements/test.txt
          python -m pip install -r requirements/pip.txt
          python -m pip install . --no-deps

      - name: Validate diffpy.srfit
        run: python -m pytest
